name: pktreplay

x-pktreplay-common: &pktreplay-common
  build:
    context: ../..
    dockerfile: containers/pktreplay-tester/Dockerfile
  command: ["sleep", "infinity"]
  stdin_open: true
  tty: true
  network_mode: host
  privileged: true

services:
  sender:
    <<: *pktreplay-common
    container_name: sender
    volumes:
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - ../../Pktgen-DPDK:/DPDK-PktReplay/Pktgen-DPDK
      - ../../data:/DPDK-PktReplay/data
      - ./scripts/sender:/DPDK-PktReplay/scripts
      - ./scripts/veth-setup.sh:/DPDK-PktReplay/veth-setup.sh
  receiver:
    <<: *pktreplay-common
    container_name: receiver
    volumes:
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - ../../data/captures:/DPDK-PktReplay/captures
      - ./scripts/receiver:/DPDK-PktReplay/scripts
      - ./scripts/veth-setup.sh:/DPDK-PktReplay/veth-setup.sh